### ISSUE TITLE
Farcase website redirects to a spammy website

### ISSUE THREAD

**Issue by web3Gurung** [farcase/farapps#13]
Hey @alvesjtiago 

The website https://farcase.xyz/ reads to a spammy website. I think there has been a domain takeover or something. See screenshot for proof. 

Even https://castalytics.farcase.xyz/ doesn't work and it redirects to http://net.domain.name/?subid1=farcase.xyz&terms=play%20online%20games,google%20server%20cloud,gmail%20account .

![2024-02-03_02-36](https://github.com/farcase/farapps/assets/72032538/3895bfb4-8564-469c-8738-3b8643b3250b)

**Comment by web3Gurung** [comment]
cc @whatrocks @davidfurlong @payton @benadamsky 
I'm sorry to mass tag, but this is quite important and y'all are the contributors who have helped farcase progress in the past.

**Comment by alvesjtiago** [comment]
Unfortunately I have not renewed the domain and I'll be migrating the sites to vercel links and potentially under a different domain. I'll update documentation this weekend.

**Comment by alvesjtiago** [comment]
URL updated on the github repo to https://farapps.vercel.app/

**Comment by web3Gurung** [comment]
Looks good, have a good day!
